// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrX2Mf4KC2vumZWl5_nJUQwP9rUu7YSc',
    appId: '1:809967253628:web:3bfb8094d951c59a2df1f9',
    messagingSenderId: '809967253628',
    projectId: 'fitness-app-5e8ff',
    authDomain: 'fitness-app-5e8ff.firebaseapp.com',
    storageBucket: 'fitness-app-5e8ff.appspot.com',
    measurementId: 'G-DEQC8S5DDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Ce2MSFlKOX8PGxZy8cl0l83gM4jrbpM',
    appId: '1:809967253628:android:8c6d02a51fde528f2df1f9',
    messagingSenderId: '809967253628',
    projectId: 'fitness-app-5e8ff',
    storageBucket: 'fitness-app-5e8ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9CeQzOlCkIHjbnfG_YpZeNrNEv53tiPQ',
    appId: '1:809967253628:ios:8d81c580520eb8f92df1f9',
    messagingSenderId: '809967253628',
    projectId: 'fitness-app-5e8ff',
    storageBucket: 'fitness-app-5e8ff.appspot.com',
    iosBundleId: 'com.example.fitnessappsih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9CeQzOlCkIHjbnfG_YpZeNrNEv53tiPQ',
    appId: '1:809967253628:ios:aef9daca9d25eb2a2df1f9',
    messagingSenderId: '809967253628',
    projectId: 'fitness-app-5e8ff',
    storageBucket: 'fitness-app-5e8ff.appspot.com',
    iosBundleId: 'com.example.fitnessappsih.RunnerTests',
  );
}
